# Generated by Django 5.2.6 on 2025-09-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcloudzone',
            options={'verbose_name': 'UpCloud Zone', 'verbose_name_plural': 'UpCloud Zones'},
        ),
        migrations.AddField(
            model_name='request',
            name='upcloud_server_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
