# Generated by Django 5.2.6 on 2025-09-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_upcloudzone_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcloudzone',
            old_name='public',
            new_name='visible',
        ),
    ]
