# Generated by Django 5.2.6 on 2025-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_public_upcloudzone_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflarezone',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
