# Generated by Django 5.2.6 on 2025-09-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_upcloudplans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpCloudPlans',
            new_name='UpCloudPlan',
        ),
    ]
