# Generated by Django 5.2.6 on 2025-09-27 17:36

import django.db.models.deletion
import request.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_rename_upcloudplans_upcloudplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='upcloud_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='request.upcloudplan'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contact_email',
            field=models.EmailField(help_text='Contact email for the party organizers', max_length=254),
        ),
        migrations.AlterField(
            model_name='request',
            name='domain',
            field=models.CharField(help_text='Subdomain for the instance without the host, usually name of the party. Accepted characters are a-z, 0-9 and hyphen (-). Example: myparty', max_length=255, validators=[request.models.domain_validator]),
        ),
        migrations.AlterField(
            model_name='request',
            name='party_url',
            field=models.URLField(blank=True, help_text="URL to the party's official website", null=True),
        ),
    ]
