# Generated by Django 5.2.10 on 2026-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_email_request_extra_info_request_inception_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Any extra information we might need. If the instance needs to be online much in advance, a reason should be given.', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='inception_date',
            field=models.DateField(help_text='Date when the instance should be online'),
        ),
    ]
