# Generated by Django 5.2.10 on 2026-02-09 20:09

import request.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_request_extra_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_mode', models.BooleanField(default=False, help_text='Sandbox mode. Bypasses all Cloudflare and UpCloud functions')),
                ('upcloud_api_username', request.models.FernetEncryptedCharField(max_length=255)),
                ('upcloud_api_password', request.models.FernetEncryptedCharField(max_length=255)),
                ('upcloud_api_url', models.CharField(max_length=255)),
                ('cloudflare_api_token', request.models.FernetEncryptedCharField(max_length=255)),
                ('cloudflare_turnstile_key', request.models.FernetEncryptedCharField(max_length=255)),
                ('cloudflare_turnstile_secret', request.models.FernetEncryptedCharField(max_length=255)),
                ('mailjet_api_key', request.models.FernetEncryptedCharField(max_length=255)),
                ('mailjet_api_secret', request.models.FernetEncryptedCharField(max_length=255)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
